### ISSUE TITLE
odseq installation causes package conflicts

### ISSUE THREAD

**Issue by nvpatin** [aomlomics/tourmaline#42]
The bioconductor-odseq package can cause problems with other dependencies and may need to be re-installed in the conda environment.

**Comment by GLomics** [comment]
Instead of using the command `conda install -c bioconda bioconductor-msa bioconductor-odseq` to install both msa and odseq, first use `conda install -c bioconda/label/gcc7 bioconductor-msa` to install msa.  
Next, go into r within your condo environment and install odseq through 
`if (!requireNamespace("BiocManager", quietly = TRUE))
    install.packages("BiocManager")
BiocManager::install("odseq")`.  
Don't update any other packages if prompted while installing odseq.  quit() your r environment and install empress through pip as described on the Tourmaline GitHub.

**Comment by lukenoaa** [comment]
Trying to install both msa and odseq gives error "Solving environment: failed ..."

Following @GLomics suggested step `conda install -c bioconda/label/gcc7 bioconductor-msa` also gives a solving environment failure, with this message: 

```
UnsatisfiableError: The following specifications were found to be incompatible with each other:

Output in format: Requested package -> Available versions

Package libcxx conflicts for:
bioconductor-msa -> libcxx[version='>=4.0.1']
bioconductor-msa -> r-rcpp[version='>=0.11.1'] -> libcxx[version='>=11.0.0']

Package zlib conflicts for:
python=3.6.13 -> zlib[version='>=1.2.11,<1.3.0a0']
bioconductor-msa -> r-base[version='>=3.5.1,<3.5.2.0a0'] -> zlib[version='>=1.2.11,<1.3.0a0']
```

**Comment by lukenoaa** [comment]
This is starting with a new environment installation of `qiime2-2021-2`.

**Comment by GLomics** [comment]
Just an initial guess, not sure if this makes sense as I was throwing everything at this issue until something worked.  What about trying to install msa through the R environment as well?  Not sure if that fixes the odseq issue, but worth a quick try.  

`if (!requireNamespace("BiocManager", quietly = TRUE))
    install.packages("BiocManager")

BiocManager::install("msa")
BiocManager::install("odseq")`

**Comment by lukenoaa** [comment]
Thank you, @GLomics! This worked perfectly.
