### ISSUE TITLE
Snakemake is re-running denoising when using filtered commands

### ISSUE THREAD

**Issue by lukenoaa** [aomlomics/tourmaline#98]
Also sometimes happens when parameters are changed that shouldn't affect denoising (DADA2) output. This shouldn't be happening if workflow is working properly, and it adds a lot of time to the workflow. Check Snakefile and DAG.

**Comment by lukenoaa** [comment]
This is probably the expected behavior (I'm assuming only the filtering and downstream steps are being done and not denoising also). There's only allowance for one set of filtering parameters, so if you want to test multiple sets of filtering parameters, you'll have to rename the old `02-output-dad2-pe-filtered` folder so it's not overwritten.

**Comment by ksilnoaa** [comment]
Recreated the bug. If you copy a tourmaline folder containing unfiltered outputs to a new folder (`cp -r`) because you want to run with new filter parameters but don't want to delete the previous run, the timestamps will change. This may lead to Tourmaline rerunning the denoising and taxonomic assignment steps during a `filtered` command, as Snakemake determines if files need to be regenerated based on timestamps. 

To avoid this, copy the Tourmaline directory with the `-p ` flag to preserve timestamps. Example:  

```
cp -rp tourmaline-old/ tourmaline-new
```
This will be mentioned in the documentation and issue closed.
